from django.urls import path
from django.views.generic import RedirectView
from . import views

app_name = 'lms'
urlpatterns = [
    path('', views.index, name='index'),
    path('search-book', views.search_book, name='search-book'),
    path('login-admin', views.login_admin, name='admin-login'),
    path('admin', RedirectView.as_view(url='admin/dashboard', permanent=True)),
    path('admin/dashboard', views.admin_dashboard, name='admin-dashboard'),
    path('admin/borrow-return', views.admin_borrow_return, name='admin-borrow-return'),
    path('admin/add-borrow-return', views.admin_add_borrow_return, name='admin-add-borrow-return'),
    path('admin/book', views.admin_book, name='admin-book'),
    path('admin/author', views.admin_author, name='admin-author'),
    path('admin/publisher', views.admin_publisher, name='admin-publisher'),
    path('admin/borrower', views.admin_borrower, name='admin-borrower'),
    path('admin/borrow-log', views.admin_borrow_log, name='admin-borrow-log'),
    path('admin/borrow-log/<int:month>/<int:year>', views.admin_borrow_log_with_date, name='admin-borrow-log-with-date'),
    path('admin/borrow-log-download/<int:month>/<int:year>', views.admin_borrow_log_pdf, name='admin-borrow-log-pdf'),
    path('admin/category', views.admin_category, name='admin-category'),
    path('admin/logout', views.admin_logout, name='admin-logout'),
    path('admin/book/add', views.admin_add_book, name='admin-add-book'),
    path('admin/book/detail/<int:book_id>', views.admin_book_detail, name='admin-book-detail'),
    path('admin/book/update/<int:book_id>', views.admin_update_book, name='admin-update-book'),
    path('admin/book/delete/<int:book_id>', views.admin_delete_book, name='admin-delete-book'),
    path('admin/borrower/add', views.admin_add_borrower, name='admin-add-borrower'),
    path('admin/borrower/detail/<int:borrower_id>', views.admin_borrower_detail, name='admin-borrower-detail'),
    path('admin/borrower/update/<int:borrower_id>', views.admin_update_borrower, name='admin-update-borrower'),
    path('admin/borrower/delete/<int:borrower_id>', views.admin_delete_borrower, name='admin-delete-borrower'),
    path('admin/borrower/member-card/<int:borrower_id>', views.admin_member_card, name='admin-member-card'),
    path('admin/author/add', views.admin_add_author, name='admin-add-author'),
    path('admin/author/detail/<int:author_id>', views.admin_author_detail, name='admin-author-detail'),
    path('admin/author/update/<int:author_id>', views.admin_update_author, name='admin-update-author'),
    path('admin/author/delete/<int:author_id>', views.admin_delete_author, name='admin-delete-author'),
    path('admin/publisher/add', views.admin_add_publisher, name='admin-add-publisher'),
    path('admin/publisher/detail/<int:publisher_id>', views.admin_publisher_detail, name='admin-publisher-detail'),
    path('admin/publisher/update/<int:publisher_id>', views.admin_update_publisher, name='admin-update-publisher'),
    path('admin/publisher/delete/<int:publisher_id>', views.admin_delete_publisher, name='admin-delete-publisher'),
    path('admin/category/add', views.admin_add_category, name='admin-add-category'),
    path('admin/category/update/<int:category_id>', views.admin_update_category, name='admin-update-category'),
    path('admin/category/delete/<int:category_id>', views.admin_delete_category, name='admin-delete-category'),
    path('admin/borrow-log/delete/<int:id>', views.admin_delete_borrow_log, name='admin-delete-borrow-log'),
]