# Generated by Django 4.0.4 on 2022-04-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year_published', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=15)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='lms.author')),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('borrower_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_description', models.CharField(max_length=100)),
                ('log_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_table', to='lms.book')),
                ('borrower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_table', to='lms.borrower')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='lms.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='books', to='lms.publisher'),
        ),
    ]
