# Generated by Django 4.0.4 on 2022-04-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_bookauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
    ]
