# Generated by Django 4.0.4 on 2022-04-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_book_author_id_book_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcategory',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='bookcategory',
            name='category_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(blank=True, related_name='books', to='lms.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_id',
            field=models.ManyToManyField(blank=True, related_name='books', to='lms.category'),
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
