# Generated by Django 4.0.4 on 2022-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_remove_bookcategory_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(null=True, related_name='books', to='lms.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_id',
            field=models.ManyToManyField(null=True, related_name='books', to='lms.category'),
        ),
    ]
