# Generated by Django 4.0.4 on 2022-04-28 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_book_isbn_alter_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlog',
            name='activity',
            field=models.CharField(default='BORROW', max_length=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_id',
            field=models.ManyToManyField(related_name='books', to='lms.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_id',
            field=models.ManyToManyField(related_name='books', to='lms.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='lms.publisher'),
        ),
    ]
