# Generated by Django 4.0.4 on 2022-04-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_borrowlog_activity_alter_book_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
