# Generated by Django 4.0.4 on 2022-04-28 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_author_name_alter_publisher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowlog',
            name='book_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_log', to='lms.book'),
        ),
        migrations.AddField(
            model_name='borrowlog',
            name='borrower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_log', to='lms.borrower'),
        ),
    ]
