# Generated by Django 4.0.4 on 2022-04-28 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_borrowlog_book_id_borrowlog_borrower_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowlog',
            name='log_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
